# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: shashank0202/docker-build-push-gcr-update-gke-deployment-action@v1.0
        with:
          service_account: ${{ secrets.GCLOUD_AUTH}}
          zone: 'europe-west2-c'
          project_id: 'sixth-loader-344609'
          registry: 'us.gcr.io'
          image_name: 'adidas_express_email'
          cluster: 'adidasttestcluster'
          namespace: 'default'
          deployment: 'adidas-express-email-depl'
          container: 'adidas-express-email'
