# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE: adidas_express_email
  REGISTRY: us.gcr.io
  CONTAINER: adidas-express-email

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: shashank0202/docker-build-push-gcr-update-gke-deployment-action@v1.0
        with:
          service_account: ${{ secrets.GCLOUD_AUTH }}
          zone: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE }}
          cluster: ${{ secrets.GKE_CLUSTER }}
          namespace: ${{ secrets.GKE_NAMESPACE }}
          deployment: ${{ secrets.GKE_DEPLOYMENT }}
          container: ${{ secrets.CONTAINER }}
